stations: # acquired form https://gml.noaa.gov/grad/surfrad/sitepage.html
  BND:
    Name: "Bondville, Illinois"
    Latitude: 40.05192
    Longitude: -88.37309
    Elevation: 230 m
    Time_Zone: "6 hours from UTC"
    Installed: "April 1994"
    emis: 0.9751  # broadband emissivity calculated from ASTER GEDv3 at prescribed lon, lat
    scene_id: '023032' # WRS-2 path and row
    bounding_box: [[[-88.764038, 39.812459], [-87.973022, 39.812459], [-87.973022, 40.34625], [-88.764038, 40.34625], [-88.764038, 39.812459]]]
  TBL:
    Name: "Table Mountain, Boulder, Colorado"
    Latitude: 40.12498
    Longitude: -105.23680
    Elevation: 1689 m
    Time_Zone: "7 hours from UTC"
    Installed: "July 1995"
    emis: 0.9711
    scene_id: '034032'
    bounding_box: [[[-105.630798, 39.85675], [-104.856262, 39.85675], [-104.856262, 40.39647], [-105.630798, 40.39647], [-105.630798, 39.85675]]]
  DRA:
    Name: "Desert Rock, Nevada"
    Latitude: 36.62373
    Longitude: -116.01947
    Elevation: 1007 m
    Time_Zone: "8 hours from UTC"
    Installed: "March 1998"
    emis: 0.9698
    scene_id: '040035'
    bounding_box: [[[-116.38916, 36.332517], [-115.787659, 36.332517], [-115.787659, 36.81997], [-116.38916, 36.81997], [-116.38916, 36.332517]]]
  FPK:
    Name: "Fort Peck, Montana"
    Latitude: 48.30783
    Longitude: -105.10170
    Elevation: 634 m
    Time_Zone: "7 hours from UTC"
    Installed: "November 1994"
    emis: 0.9791
    scene_id: '036026'
    bounding_box: [[[-105.225677, 48.221799], [-104.949646, 48.221799], [-104.949646, 48.398081], [-105.225677, 48.398081], [-105.225677, 48.221799]]]
  GWN:
    Name: "Goodwin Creek, Mississippi"
    Latitude: 34.2547
    Longitude: -89.8729
    Elevation: 98 m
    Time_Zone: "6 hours from UTC"
    Installed: "December 1994"
    emis: 0.9690
    scene_id: '023036'
    bounding_box: [[[-90.277405, 34.06169], [-89.601746, 34.06169], [-89.601746, 34.635397], [-90.277405, 34.635397], [-90.277405, 34.06169]]]
  PSU:
    Name: "Penn. State Univ., Pennsylvania"
    Latitude: 40.72012
    Longitude: -77.93085
    Elevation: 376 m
    Time_Zone: "5 hours from UTC"
    Installed: "June 1998"
    emis: 0.9717
    scene_id: '016032'
    bounding_box: [[[-78.305054, 40.530371], [-77.536011, 40.530371], [-77.536011, 41.054373], [-78.305054, 41.054373], [-78.305054, 40.530371]]]
  SXF:
    Name: "Sioux Falls, South Dakota"
    Latitude: 43.73403
    Longitude: -96.62328
    Elevation: 473 m
    Time_Zone: "6 hours from UTC"
    Installed: "June 2003"
    emis: 0.9727
    scene_id: '029030'
    bounding_box: [[[-97.176819, 43.379039], [-96.416016, 43.379039], [-96.416016, 43.933444], [-97.176819, 43.933444], [-97.176819, 43.379039]]]
  SGP:
    Name: "ARM Southern Great Plains Facility, Oklahoma"
    Latitude: 36.60406
    Longitude: -97.48525
    Elevation: 314 m
    Time_Zone: "6 hours from UTC"
    emis: 0.9743
    scene_id: '028035'
    bounding_box: [[[-98.014526, 36.270781], [-97.319641, 36.270781], [-97.319641, 36.824608], [-98.014526, 36.824608], [-98.014526, 36.270781]]]

# Define the column names based on the Fortran code variables and their quality control indicators
column_names : [
     'year', 'jday', 'month', 'day', 'hour', 'min',
     'dt', 'zen', 'dw_solar', 'qc_dwsolar', 'uw_solar', 'qc_uwsolar', 'direct_n',
     'qc_direct_n', 'diffuse', 'qc_diffuse', 'dw_ir', 'qc_dwir', 'dw_casetemp',
     'qc_dwcasetemp', 'dw_dometemp', 'qc_dwdometemp', 'uw_ir', 'qc_uwir', 'uw_casetemp',
     'qc_uwcasetemp', 'uw_dometemp', 'qc_uwdometemp', 'uvb', 'qc_uvb', 'par', 'qc_par',
     'netsolar', 'qc_netsolar', 'netir', 'qc_netir', 'totalnet', 'qc_totalnet', 'temp',
     'qc_temp', 'rh', 'qc_rh', 'windspd', 'qc_windspd', 'winddir', 'qc_winddir',
     'pressure', 'qc_pressure']

