stations: # acquired form https://gml.noaa.gov/grad/surfrad/sitepage.html
  BND:
    Name: "Bondville, Illinois"
    Latitude: 40.05192
    Longitude: -88.37309
    Elevation: 230 m
    Time_Zone: "6 hours from UTC"
    Installed: "April 1994"
    emis: 0.9751  # broadband emissivity calculated from ASTER GEDv3 at prescribed lon, lat
  TBL:
    Name: "Table Mountain, Boulder, Colorado"
    Latitude: 40.12498
    Longitude: -105.23680
    Elevation: 1689 m
    Time_Zone: "7 hours from UTC"
    Installed: "July 1995"
    emis: 0.9711
  DRA:
    Name: "Desert Rock, Nevada"
    Latitude: 36.62373
    Longitude: -116.01947
    Elevation: 1007 m
    Time_Zone: "8 hours from UTC"
    Installed: "March 1998"
    emis: 0.9698
  FPK:
    Name: "Fort Peck, Montana"
    Latitude: 48.30783
    Longitude: -105.10170
    Elevation: 634 m
    Time_Zone: "7 hours from UTC"
    Installed: "November 1994"
    emis: 0.9791
  GWN:
    Name: "Goodwin Creek, Mississippi"
    Latitude: 34.2547
    Longitude: -89.8729
    Elevation: 98 m
    Time_Zone: "6 hours from UTC"
    Installed: "December 1994"
    emis: 0.9690
  PSU:
    Name: "Penn. State Univ., Pennsylvania"
    Latitude: 40.72012
    Longitude: -77.93085
    Elevation: 376 m
    Time_Zone: "5 hours from UTC"
    Installed: "June 1998"
    emis: 0.9717
  SXF:
    Name: "Sioux Falls, South Dakota"
    Latitude: 43.73403
    Longitude: -96.62328
    Elevation: 473 m
    Time_Zone: "6 hours from UTC"
    Installed: "June 2003"
    emis: 0.9727
  SGP:
    Name: "ARM Southern Great Plains Facility, Oklahoma"
    Latitude: 36.60406
    Longitude: -97.48525
    Elevation: 314 m
    Time_Zone: "6 hours from UTC"
    emis: 0.9743

# Define the column names based on the Fortran code variables and their quality control indicators
column_names : [
     'year', 'jday', 'month', 'day', 'hour', 'min',
     'dt', 'zen', 'dw_solar', 'qc_dwsolar', 'uw_solar', 'qc_uwsolar', 'direct_n',
     'qc_direct_n', 'diffuse', 'qc_diffuse', 'dw_ir', 'qc_dwir', 'dw_casetemp',
     'qc_dwcasetemp', 'dw_dometemp', 'qc_dwdometemp', 'uw_ir', 'qc_uwir', 'uw_casetemp',
     'qc_uwcasetemp', 'uw_dometemp', 'qc_uwdometemp', 'uvb', 'qc_uvb', 'par', 'qc_par',
     'netsolar', 'qc_netsolar', 'netir', 'qc_netir', 'totalnet', 'qc_totalnet', 'temp',
     'qc_temp', 'rh', 'qc_rh', 'windspd', 'qc_windspd', 'winddir', 'qc_winddir',
     'pressure', 'qc_pressure']

