stations: # acquired form https://gml.noaa.gov/grad/surfrad/sitepage.html
  BND:
    Name: "Bondville, Illinois"
    Latitude: 40.05192
    Longitude: -88.37309
    Elevation: 230 m
    Time_Zone: "6 hours from UTC"
    Installed: "April 1994"
  TBL:
    Name: "Table Mountain, Boulder, Colorado"
    Latitude: 40.12498
    Longitude: -105.23680
    Elevation: 1689 m
    Time_Zone: "7 hours from UTC"
    Installed: "July 1995"
  DRA:
    Name: "Desert Rock, Nevada"
    Latitude: 36.62373
    Longitude: -116.01947
    Elevation: 1007 m
    Time_Zone: "8 hours from UTC"
    Installed: "March 1998"
  FPK:
    Name: "Fort Peck, Montana"
    Latitude: 48.30783
    Longitude: -105.10170
    Elevation: 634 m
    Time_Zone: "7 hours from UTC"
    Installed: "November 1994"
  GWN:
    Name: "Goodwin Creek, Mississippi"
    Latitude: 34.2547
    Longitude: -89.8729
    Elevation: 98 m
    Time_Zone: "6 hours from UTC"
    Installed: "December 1994"
  PSU:
    Name: "Penn. State Univ., Pennsylvania"
    Latitude: 40.72012
    Longitude: -77.93085
    Elevation: 376 m
    Time_Zone: "5 hours from UTC"
    Installed: "June 1998"
  SXF:
    Name: "Sioux Falls, South Dakota"
    Latitude: 43.73403
    Longitude: -96.62328
    Elevation: 473 m
    Time_Zone: "6 hours from UTC"
    Installed: "June 2003"
  SGP:
    Name: "ARM Southern Great Plains Facility, Oklahoma"
    Latitude: 36.60406
    Longitude: -97.48525
    Elevation: 314 m
    Time_Zone: "6 hours from UTC"

# Define the column names based on the Fortran code variables and their quality control indicators
column_names : [
     'year', 'jday', 'month', 'day', 'hour', 'min',
     'dt', 'zen', 'dw_solar', 'qc_dwsolar', 'uw_solar', 'qc_uwsolar', 'direct_n',
     'qc_direct_n', 'diffuse', 'qc_diffuse', 'dw_ir', 'qc_dwir', 'dw_casetemp',
     'qc_dwcasetemp', 'dw_dometemp', 'qc_dwdometemp', 'uw_ir', 'qc_uwir', 'uw_casetemp',
     'qc_uwcasetemp', 'uw_dometemp', 'qc_uwdometemp', 'uvb', 'qc_uvb', 'par', 'qc_par',
     'netsolar', 'qc_netsolar', 'netir', 'qc_netir', 'totalnet', 'qc_totalnet', 'temp',
     'qc_temp', 'rh', 'qc_rh', 'windspd', 'qc_windspd', 'winddir', 'qc_winddir',
     'pressure', 'qc_pressure']

#SURFRAD_station_locations: # high resolution coordinates acquired from https://gml.noaa.gov/grad/surfrad/sitepage.html
#  Penn_State:
#    Tower: {lat: 40.72033, lon: -77.93100}
#    Tracker: {lat: 40.72023, lon: -77.93090}
#    Platform: {lat: 40.72012, lon: -77.93085}
#  Fort_Peck:
#    Tower: {lat: 48.30798, lon: -105.10177}
#    Tracker: {lat: 48.30780, lon: -105.10172}
#    Platform: {lat: 48.30783, lon: -105.10170}
#  Bondville:
#    Tower: {lat: 40.05155, lon: -88.37325}
#    Tracker: {lat: 40.05195, lon: -88.37310}
#    Platform: {lat: 40.05192, lon: -88.37309}
#  Table_Mountain:
#    Tower: {lat: 40.12557, lon: -105.23775}
#    Tracker: {lat: 40.12493, lon: -105.23677}
#    Platform: {lat: 40.12498, lon: -105.23680}
#  Desert_Rock:
#    Tower: {lat: 36.62320, lon: -116.01962}
#    Tracker: {lat: 36.62387, lon: -116.01948}
#    Platform: {lat: 36.62373, lon: -116.01947}
#  Sioux_Falls:
#    Tower: {lat: 43.73431, lon: -96.62334}
#    Tracker: {lat: 43.73399, lon: -96.62328}
#    Platform: {lat: 43.73403, lon: -96.62328}
#  Goodwin_Creek:
#    Tracker: {lat: 34.2547, lon: -89.8729}