# python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/New York"
python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/Los Angeles"
python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/Chicago"
python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/Houston"
python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/Phoenix"
python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/Philadelphia"
python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/San Antonio"

python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/Indianapolis"
python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/Charlotte"
python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/San Francisco"
python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/Seattle"
python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/Denver"
# python main_lst.py --dir "/home/yuhaoliu/Data/ISLAND/cities/Oklahoma City"